version: '3.8'
services:
  todo-nest:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    networks:
      - todo_nest_network
networks:
  todo_nest_network:
